# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Jude Workflow

on:
  workflow_dispatch:
    inputs:
      some_string:
        type: string
        default: default value goes here
        description: Provide a string value here, otherwise defaults to something
      select:
        type: choice
        description: Selection thingy
        options:
          - uno
          - dos
          - tres
          - 1
          - 2
      some_number:
        type: number
        description: Put in a number here
        default: but the placeholder can be not a number
        required: true
      some_boolean:
        type: boolean
        description: You know what this is

jobs:
  the-first-job:
    runs-on: ubuntu-latest
    outputs:
      var-for-outside: ${{ steps.config-vars.outputs.the_var }}
    steps:
      - name: Display inputs
        run: echo "${{ toJSON(inputs) }}"
      - name: Config vars
        id: config-vars
        run: |
          case "${{ inputs.select }}" in
            uno)
              THE_VAR=one
              ;;
            dos)
              THE_VAR=two
              ;;
            tres)
              THE_VAR=three
              ;;
          esac

          echo "the_var=${THE_VAR}" >> ${GITHUB_OUTPUT}
      - name: Use Variable Within Job
        id: use-variable
        run: |
          echo "The variable value is: ${{steps.config-vars.outputs.the_var}}"
  the-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use var from another job
        id: use-var-from-another
        run: |
          echo "The value from outside is: ${{ needs.jobs.the-first-job.outputs.the_var }}"

